import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="text-center p-8 flex gap-6 border items-center justify-center ">
          {" "}
          <h4 className="text-4xl text-center uppercase text-green-500">
            My Next.js App
          </h4>
          <a href="/" className="text-green-500 hover:underline">
            Home
          </a>
          <a href="/users/new" className="text-green-500 hover:underline">
            New User
          </a>
          <a href="/users" className="text-green-500 hover:underline">
            All Users
          </a>
        </div>
        {children}
      </body>
    </html>
  );
}
